#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.138                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = 
CFLAGS =  -Wall
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = 

INC_DEBUG =  $(INC)
CFLAGS_DEBUG =  $(CFLAGS) -g
RESINC_DEBUG =  $(RESINC)
RCFLAGS_DEBUG =  $(RCFLAGS)
LIBDIR_DEBUG =  $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG =  $(LDFLAGS)
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG = 
OUT_DEBUG = bin/Debug/zMemPool

INC_RELEASE =  $(INC)
CFLAGS_RELEASE =  $(CFLAGS) -O2
RESINC_RELEASE =  $(RESINC)
RCFLAGS_RELEASE =  $(RCFLAGS)
LIBDIR_RELEASE =  $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE =  $(LDFLAGS) -s
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = bin/Release/zMemPool

OBJ_DEBUG = $(OBJDIR_DEBUG)/dependency/CException.o $(OBJDIR_DEBUG)/dependency/unity.o $(OBJDIR_DEBUG)/main.o $(OBJDIR_DEBUG)/zMemPool.o $(OBJDIR_DEBUG)/zMemPool_Test.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/dependency/CException.o $(OBJDIR_RELEASE)/dependency/unity.o $(OBJDIR_RELEASE)/main.o $(OBJDIR_RELEASE)/zMemPool.o $(OBJDIR_RELEASE)/zMemPool_Test.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	test -d bin/Debug || mkdir -p bin/Debug
	test -d $(OBJDIR_DEBUG)/dependency || mkdir -p $(OBJDIR_DEBUG)/dependency
	test -d $(OBJDIR_DEBUG) || mkdir -p $(OBJDIR_DEBUG)

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/dependency/CException.o: dependency/CException.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c dependency/CException.c -o $(OBJDIR_DEBUG)/dependency/CException.o

$(OBJDIR_DEBUG)/dependency/unity.o: dependency/unity.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c dependency/unity.c -o $(OBJDIR_DEBUG)/dependency/unity.o

$(OBJDIR_DEBUG)/main.o: main.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c main.c -o $(OBJDIR_DEBUG)/main.o

$(OBJDIR_DEBUG)/zMemPool.o: zMemPool.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c zMemPool.c -o $(OBJDIR_DEBUG)/zMemPool.o

$(OBJDIR_DEBUG)/zMemPool_Test.o: zMemPool_Test.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c zMemPool_Test.c -o $(OBJDIR_DEBUG)/zMemPool_Test.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf bin/Debug
	rm -rf $(OBJDIR_DEBUG)/dependency
	rm -rf $(OBJDIR_DEBUG)

before_release: 
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_RELEASE)/dependency || mkdir -p $(OBJDIR_RELEASE)/dependency
	test -d $(OBJDIR_RELEASE) || mkdir -p $(OBJDIR_RELEASE)

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/dependency/CException.o: dependency/CException.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c dependency/CException.c -o $(OBJDIR_RELEASE)/dependency/CException.o

$(OBJDIR_RELEASE)/dependency/unity.o: dependency/unity.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c dependency/unity.c -o $(OBJDIR_RELEASE)/dependency/unity.o

$(OBJDIR_RELEASE)/main.o: main.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c main.c -o $(OBJDIR_RELEASE)/main.o

$(OBJDIR_RELEASE)/zMemPool.o: zMemPool.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c zMemPool.c -o $(OBJDIR_RELEASE)/zMemPool.o

$(OBJDIR_RELEASE)/zMemPool_Test.o: zMemPool_Test.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c zMemPool_Test.c -o $(OBJDIR_RELEASE)/zMemPool_Test.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin/Release
	rm -rf $(OBJDIR_RELEASE)/dependency
	rm -rf $(OBJDIR_RELEASE)

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

